# Library

In [1]:
from ultralytics import YOLO
import cv2 

# load models

In [2]:
# model untuk deteksi mobil
model_mobil = YOLO(r"D:\Belajar FR\Youtube_2\plate-detection\yolo11n.pt")

# model untuk deteksi plat nomor
model_plat = YOLO(r"D:\Belajar FR\Youtube_2\plate-detection\model_plate_detection.pt")


# load video

In [3]:
cap =cv2.VideoCapture(r"D:\Belajar FR\Youtube_2\plate-detection\sample.mp4")

# read frame

In [ ]:
# melihat isi dari hasil pembacaan frame video

frame_number = -1 # inisiasi frame awal karena akan membaca dari 0
succes = True
while succes:
    frame_number += 1 
    succes, frame = cap.read()
    if succes and frame_number < 1: # membaca frame pertama (0) untuk debug (memberi batas untuk lihat isi saja)
        detection = model_mobil(frame)[0] # memanggil model untuk membaca frame pertama
        print(detection) # mencetak hasil deteksi
    else:
        break


0: 384x640 16 cars, 5 trucks, 146.8ms
Speed: 410.7ms preprocess, 146.8ms inference, 5.6ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 

In [66]:
frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]
        box = detection.boxes
        print(box)
    else:
        break


0: 384x640 17 cars, 1 bus, 4 trucks, 147.4ms
Speed: 466.2ms preprocess, 147.4ms inference, 3.9ms postprocess per image at shape (1, 3, 384, 640)
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([2., 2., 2., 2., 2., 2., 2., 7., 7., 2., 7., 2., 7., 2., 2., 2., 2., 2., 5., 2., 2., 2.], device='cuda:0')
conf: tensor([0.8720, 0.8435, 0.8121, 0.7985, 0.7924, 0.7867, 0.7365, 0.6529, 0.6410, 0.5589, 0.5145, 0.4818, 0.4798, 0.4739, 0.4723, 0.4653, 0.4410, 0.3508, 0.3164, 0.3051, 0.2501, 0.2500], device='cuda:0')
data: tensor([[7.5222e+02, 1.7235e+03, 1.4090e+03, 2.1590e+03, 8.7195e-01, 2.0000e+00],
        [9.7000e+02, 1.2398e+03, 1.5879e+03, 1.8225e+03, 8.4353e-01, 2.0000e+00],
        [7.7606e+01, 6.6072e+02, 3.9725e+02, 9.2769e+02, 8.1206e-01, 2.0000e+00],
        [2.1915e+03, 1.0045e+03, 2.6619e+03, 1.4033e+03, 7.9854e-01, 2.0000e+00],
        [2.3185e+03, 1.1872e+03, 2.9596e+03, 1.6366e+03, 7.9236e-01, 2.0000e+00],
        [2.1880e+03, 7.8140e+02, 2.5166e+03, 1.0502e+0

In [67]:
frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]
        box = detection.boxes
        print(dir(box))
    else:
        break



0: 384x640 15 cars, 1 bus, 4 trucks, 146.8ms
Speed: 437.7ms preprocess, 146.8ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cls', 'conf', 'cpu', 'cuda', 'data', 'id', 'is_track', 'numpy', 'orig_shape', 'shape', 'to', 'xywh', 'xywhn', 'xyxy', 'xyxyn']


In [ ]:
frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]
        for box in detection.boxes.data.tolist():
            print(box)
            # outputnya akan isi dari box yaitu [x1, y1, x2, y2, conf, cls]
    else:
        break


0: 384x640 16 cars, 1 bus, 6 trucks, 147.7ms
Speed: 436.9ms preprocess, 147.7ms inference, 4.3ms postprocess per image at shape (1, 3, 384, 640)
[997.4646606445312, 1217.489013671875, 1594.524169921875, 1791.6689453125, 0.8756555914878845, 2.0]
[773.361328125, 1680.090576171875, 1412.5361328125, 2158.3173828125, 0.8628881573677063, 2.0]
[2196.40185546875, 991.5579833984375, 2625.11083984375, 1380.4454345703125, 0.7825732827186584, 2.0]
[2306.16455078125, 1177.31640625, 2910.33056640625, 1638.35888671875, 0.7722126245498657, 2.0]
[2925.673583984375, 899.4127197265625, 3377.43603515625, 1282.243896484375, 0.7601862549781799, 2.0]
[50.37081527709961, 668.8386840820312, 382.3316650390625, 935.851318359375, 0.7339485883712769, 2.0]
[2187.5810546875, 779.0289916992188, 2517.8193359375, 1039.4345703125, 0.7029569745063782, 2.0]
[1135.299072265625, 1131.1160888671875, 1618.154541015625, 1559.585205078125, 0.6189662218093872, 2.0]
[2026.0184326171875, 513.6331787109375, 2313.73779296875, 853.02

In [4]:
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]

        detection_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf])
                print(detection_2)
    else:
        break



0: 384x640 1 person, 12 cars, 1 bus, 4 trucks, 582.9ms
Speed: 93.7ms preprocess, 582.9ms inference, 193.0ms postprocess per image at shape (1, 3, 384, 640)
[[1155.695556640625, 1309.77880859375, 1646.25732421875, 1791.2568359375, 0.8260876536369324]]
[[1155.695556640625, 1309.77880859375, 1646.25732421875, 1791.2568359375, 0.8260876536369324], [761.72607421875, 1373.7020263671875, 1435.12060546875, 1975.648681640625, 0.8190982341766357]]
[[1155.695556640625, 1309.77880859375, 1646.25732421875, 1791.2568359375, 0.8260876536369324], [761.72607421875, 1373.7020263671875, 1435.12060546875, 1975.648681640625, 0.8190982341766357], [506.03302001953125, 1962.7554931640625, 1172.3602294921875, 2155.13330078125, 0.7679232954978943]]
[[1155.695556640625, 1309.77880859375, 1646.25732421875, 1791.2568359375, 0.8260876536369324], [761.72607421875, 1373.7020263671875, 1435.12060546875, 1975.648681640625, 0.8190982341766357], [506.03302001953125, 1962.7554931640625, 1172.3602294921875, 2155.133300781

# tracking vehicles

In [6]:
from sort import *
import numpy as np

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]

        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf])                             
    else:
        break

    tracks_id = tracker.update(np.array(detection_2))
    print(tracks_id)



0: 384x640 13 cars, 1 bus, 3 trucks, 62.0ms
Speed: 886.7ms preprocess, 62.0ms inference, 6.6ms postprocess per image at shape (1, 3, 384, 640)
[[     2296.7      1720.3        3330        2155          17]
 [      294.2      536.08      612.23      863.92          16]
 [     1404.9      663.91      1694.2      841.65          15]
 [     2116.5      683.01      2428.9      883.17          14]
 [     1296.7      841.67      1662.4      1057.5          13]
 [     293.88      541.76      612.08      865.41          12]
 [     1483.4      772.33      1787.7      1074.5          11]
 [      596.1      578.75       825.3      775.92          10]
 [     2108.2       448.3      2418.5         701           9]
 [     2293.4      1715.5      3322.2      2150.8           8]
 [     2038.1      882.03      2439.4      1231.7           7]
 [     3.5696      686.91      376.82      971.95           6]
 [        508      1997.2      1130.7      2155.7           5]
 [     1243.2      1020.4      1740.8 

# deteksi plat

In [ ]:
from sort import *
import numpy as np

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]

        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf])                             
    else:
        break

    tracks_id = tracker.update(np.array(detection_2))
    
    plat = model_plat(frame)[0]
    for box in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box 

# mengkoneksikan plat dengan mobilnya

In [ ]:
from sort import *
import numpy as np
from util import get_car

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]

        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf]) # informasi bbox mobil                            
    else:
        break

    tracks_id = tracker.update(np.array(detection_2))# berisikan informasi tentang bbox mobil
    
    plat = model_plat(frame)[0]
    for box_plat in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box_plat 

        # koneksikan plat ke mobil
        xcar1, ycar1, xcar2, ycar2, car_id = get_car(box_plat, tracks_id)



0: 384x640 15 cars, 4 trucks, 147.3ms
Speed: 447.4ms preprocess, 147.3ms inference, 5.7ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 License_Plates, 99.0ms
Speed: 5.3ms preprocess, 99.0ms inference, 3.9ms postprocess per image at shape (1, 3, 384, 640)


# crop plate

In [ ]:
from sort import *
import numpy as np
from util import get_car

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]

        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf]) # informasi bbox mobil                            
    else:
        break

    tracks_id = tracker.update(np.array(detection_2))# berisikan informasi tentang bbox mobil
    
    plat = model_plat(frame)[0]
    for box_plat in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box_plat 

        # koneksikan plat ke mobil
        xcar1, ycar1, xcar2, ycar2, car_id = get_car(box_plat, tracks_id)

        # crop plat
        crop_plat = frame[int(y1):int(y2), int(x1):int(x2), :]

# proses plat

In [98]:
from sort import *
import numpy as np
from util import get_car
import matplotlib.pyplot as plt

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]


        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf]) # informasi bbox mobil       
    else:
        break           

    tracks_id = tracker.update(np.array(detection_2))# berisikan informasi tentang bbox mobil
    
    plat = model_plat(frame)[0]
    for box_plat in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box_plat 

        # koneksikan plat ke mobil
        xcar1, ycar1, xcar2, ycar2, car_id = get_car(box_plat, tracks_id)

        # crop plat
        crop_plat = frame[int(y1):int(y2), int(x1):int(x2), :]

        # proses plat
        crop_plat_gray = cv2.cvtColor(crop_plat, cv2.COLOR_BGR2GRAY)
        _, crop_plat_thresh = cv2.threshold(crop_plat_gray, 64, 255, cv2.THRESH_BINARY_INV)

plt.figure(figsize=(4,3))
plt.imshow(cv2.cvtColor(crop_plat, cv2.COLOR_BGR2RGB))
plt.title("original_crop")
plt.axis("off")

plt.figure(figsize=(4,3))
plt.imshow(crop_plat_thresh, cmap="gray")
plt.title("crop_plat_thresh")
plt.axis("off")

plt.show()


0: 384x640 2 persons, 16 cars, 1 bus, 3 trucks, 266.9ms
Speed: 8.2ms preprocess, 266.9ms inference, 2.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 License_Plate, 94.1ms
Speed: 3.7ms preprocess, 94.1ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)


# mendeteksi isi plat nomor

In [ ]:
from sort import *
import numpy as np
from util import get_car
from util import read_license_plate

tracker = Sort()

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes and frame_number < 1:
        detection = model_mobil(frame)[0]


        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf]) # informasi bbox mobil       
    else:
        break           

    tracks_id = tracker.update(np.array(detection_2))# berisikan informasi tentang bbox mobil
    
    plat = model_plat(frame)[0]
    for box_plat in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box_plat 

        # koneksikan plat ke mobil
        xcar1, ycar1, xcar2, ycar2, car_id = get_car(box_plat, tracks_id)

        # crop plat
        crop_plat = frame[int(y1):int(y2), int(x1):int(x2), :]

        # proses plat
        crop_plat_gray = cv2.cvtColor(crop_plat, cv2.COLOR_BGR2GRAY)
        _, crop_plat_thresh = cv2.threshold(crop_plat_gray, 64, 255, cv2.THRESH_BINARY_INV)

        # membaca isi plat nomor
        plat_text, plat_score = read_license_plate(crop_plat_thresh)


# hasil

In [117]:
from sort import *
import numpy as np
from util import get_car, read_license_plate, write_csv
import numpy as np

tracker = Sort()

result = {}

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"
              ]

vehicles = [2, 3, 5, 7]

frame_number = -1
succes = True
while succes:
    frame_number += 1
    succes, frame = cap.read()
    if succes:
        if frame_number > 12:
            break
        result[frame_number] = {}

        detection = model_mobil(frame)[0]
        detection_2 = []
        box_2 = []
        for box in detection.boxes.data.tolist():
            x1, y1, x2, y2, conf, cls_id = box            
            if int(cls_id) in vehicles:
                detection_2.append([x1, y1, x2, y2, conf]) # informasi bbox mobil       
    # else:
    #     break           

    tracks_id = tracker.update(np.array(detection_2))# berisikan informasi tentang bbox mobil
    
    plat = model_plat(frame)[0]
    for box_plat in plat.boxes.data.tolist():
        x1, y1, x2, y2, conf, cls_id = box_plat 

        # koneksikan plat ke mobil
        xcar1, ycar1, xcar2, ycar2, car_id = get_car(box_plat, tracks_id)

        if car_id != -1:
            # crop plat
            crop_plat = frame[int(y1):int(y2), int(x1):int(x2), :]

            # proses plat
            crop_plat_gray = cv2.cvtColor(crop_plat, cv2.COLOR_BGR2GRAY)
            _, crop_plat_thresh = cv2.threshold(crop_plat_gray, 64, 255, cv2.THRESH_BINARY_INV)

            # membaca isi plat nomor
            plat_text, plat_score = read_license_plate(crop_plat_thresh)

            if plat_text is not None:
                result[frame_number][car_id] = {"car": {"bbox": [xcar1, ycar1, xcar2, ycar2]},
                                                "license_plate": {"bbox":[x1, y1, x2, y2],
                                                            "text": plat_text,
                                                            "bbox_score": conf,
                                                            "text_score": plat_score}}


# menulis hasil
write_csv(result, "./test2.csv")


0: 384x640 16 cars, 1 bus, 1 truck, 193.6ms
Speed: 27.5ms preprocess, 193.6ms inference, 10.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 License_Plate, 196.5ms
Speed: 7.7ms preprocess, 196.5ms inference, 6.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 16 cars, 1 bus, 1 truck, 189.3ms
Speed: 20.7ms preprocess, 189.3ms inference, 4.8ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 License_Plate, 95.1ms
Speed: 5.9ms preprocess, 95.1ms inference, 5.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 18 cars, 1 truck, 130.6ms
Speed: 28.2ms preprocess, 130.6ms inference, 7.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 License_Plate, 174.2ms
Speed: 13.0ms preprocess, 174.2ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 14 cars, 1 bus, 290.6ms
Speed: 23.2ms preprocess, 290.6ms inference, 2.9ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 License_Plate, 95.8ms